alias ascript="autoscript"
alias tangren="rprint 612-86-92"
alias cdaw="cd ~/.config/awesome/"
alias cdnv="cd ~/.config/nvim/"
alias nvar="nvim ~/.config/awesome/rc.lua"
alias nvat="nvim ~/.config/awesome/themes/rainbow/theme.lua"
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias nvtm="nvim .tmux.conf"
alias cds="cd ~/.scripts"
alias mkd="mkdir -pv"
alias ssn="sudo shutdown now"
alias pvpn="sudo privatvpn"
alias nvzr="nvim ~/.zshrc"
alias e="exit"
alias la="ls -AlhF --group-directories-first --color=always"
alias ls="ls -AhF --group-directories-first --color=always"
alias xst="dex ~/.local/share/applications/xst.desktop"
alias tmux="TERM=screen-256color-bce tmux"
alias clr="clear"
alias rldzsh="source ~/.zshrc"
alias pmp="python manage.py"
alias vi="nvim"
alias noblank="xset dpms 0 0 0 && xset s off && xset s noblank && ~/.fehbg"
alias aurmanauto="aurman --noconfirm --noedit"
alias la="lsd -al1 --color always --group-dirs first"
alias ls="lsd -a --color always --group-dirs first"
alias l="lsd --color always --group-dirs first"
alias L="lsd -1 --color always --group-dirs first"
alias La="lsd -a1 --color always --group-dirs first"
alias cam="mpv rtsp://admin:123456@192.168.2.25:554/profile1"
