#!/bin/bash
print-empty-line ()
{
    local c=$((fl-2))
    local d=$(printf "%-${c}s" " ")
    echo "|${d}|"
}

print-grid-line ()
{
    local a=$1
    local b=$2
    local c=$((fl-2))
    local d=$(printf "%-${c}s" "$a")
    echo "${b}${d// /-}${b}"
}

print-date ()
{
    IFS='.' read -ra line <<< $1
    local formattedDate=${line[2]}-${line[1]}-${line[0]}
    local a="$(date -d $formattedDate +%A)"
    local b="${1} ( ${a} )"
    local c=$((fl-${#b}-2))
    local d=$((c/2))
    local e=$((d+c%2))
    local f=$(printf "%-${e}s" " ")
    local g=$(printf "%-${d}s" " ")
    print-empty-line
    echo "|${f}${b}${g}|"
    print-empty-line
    print-grid-line "-" "+"
}

get-info ()
{
    TA="0"
    TD="0"
    for (( l = 0; l < ${#lines[@]}; l++)); do
        IFS=' ' read -r s1 s2 s3 <<< ${lines[l]}
        if [ $s1 = $1 ] && [ $s2 = $2 ] && [ $TA = "0" ]
        then
            TA=$s3
        elif [ $s1 = $1 ] && [ $s2 != $2 ] && [ $TA != "0" ] && [ $TD = "0" ]
        then
            IFS=' ' read -r s1 s2 s3 <<< ${lines[l-1]}
            TD=$s3
        elif [ $s1 != $1 ] && [ $s2 != $2 ] && [ $TA != "0" ] && [ $TD = "0" ]
        then
            IFS=' ' read -r s1 s2 s3 <<< ${lines[l-1]}
            TD=$s3
        elif [ $l = $((${#lines[@]}-1))  ] && [ $TA != "0" ] && [ $TD = "0" ]
        then
            IFS=' ' read -r s1 s2 s3 <<< ${lines[l]}
            TD=$s3
        fi
    done
    local a=$((ml-${#2}))
    if [ $a != 0 ]
    then
        local b=$(printf "%-${a}s" " ")
        echo "| ${2}${b} | ${TA} - ${TD} |"
    else
        echo "| ${2} | ${TA} - ${TD} |"
    fi
}

get-names ()
{
    k=0
    for ((j = 0; j < ${#lines[@]}; j++)); do
        IFS=' ' read -r s1 s2 s3 <<< ${lines[j]}
        if [ $s1 = $1 ]
        then
            if [ $s2 != $NAME ]
            then
                NAME=$s2
                names[k]=$s2
                k=$((k+1))
            fi
        fi
    done
    for (( k = 0; k < ${#names[@]}; k++)); do
        get-info $1 ${names[k]}
        if [ $k != $((${#names[@]}-1)) ]
        then
            print-grid-line "-" "+"
        fi
    done
}

input="/dev/stdin"
DATE="0"
i=0
while IFS='\n' read -r line
do
    lines[i]=$line
    i=$((i+1))
done < $input
#printf '%s\n' "${lines[@]}"
ml=0
j=0
for ((i = 0; i < ${#lines[@]}; i++)); do
    str=${lines[i]}
    IFS=' ' read -r s1 s2 s3 <<< $str
    if [ $s1 != $DATE ]
    then
        DATE=$s1
        dates[j]=$s1
        j=$((j+1))
    fi
    l=${#s2}
    if [ $ml -lt $l ]
    then
        ml=${#s2}
    fi
done
fl=$((ml+20))
for ((i = 0; i < ${#dates[@]}; i++)); do
    NAME="0"
    unset names
    print-grid-line "-" "+"
    print-date ${dates[i]}
    get-names ${dates[i]}
    print-grid-line "-" "+"
    printf '\n'
done

